[workspace]
authors = ["clintval <valentine.clint@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "sasscode"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "cargo build --release"
test = "cargo test --all --no-fail-fast --verbose"
fmt = "cargo fmt"
fmt-check = "cargo fmt -- --check"
lint = "cargo clippy --all-targets --all-features -- -D warnings"

[dependencies]
rust = ">=1.91"

[feature.benchmarking.dependencies]
splitcode = "*"
fqtk = "*"
fgbio = "*"
samtools = "*"
seqspec = "*"

[environments]
benchmarking = ["benchmarking"]
